export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const ADMIN_PRODUCTS_REQUEST = "ADMIN_PRODUCTS_REQUEST";
export const ADMIN_PRODUCTS_SUCCESS = "ADMIN_PRODUCTS_SUCCESS";
export const ADMIN_PRODUCTS_FAIL = "ADMIN_PRODUCTS_FAIL";

export const ADMIN_DELETE_PRODUCTS_REQUEST = "ADMIN_DELETE_PRODUCTS_REQUEST";
export const ADMIN_DELETE_PRODUCTS_SUCCESS = "ADMIN_DELETE_PRODUCTS_SUCCESS";
export const ADMIN_DELETE_PRODUCTS_FAIL = "ADMIN_DELETE_PRODUCTS_FAIL";

//Action Constants for Product Details
export const ALL_PRODUCTSDETAILS_REQUEST = "ALL_PRODUCTSDETAILS_REQUEST";
export const ALL_PRODUCTSDETAILS_SUCCESS = "ALL_PRODUCTSDETAILS_SUCCESS";
export const ALL_PRODUCTSDETAILS_FAIL = "ALL_PRODUCTSDETAILS_FAIL";

export const ADMIN_CREATE_PRODUCT_REQUEST = "ADMIN_CREATE_PRODUCT_REQUEST";
export const ADMIN_CREATE_PRODUCT_SUCCESS = "ADMIN_CREATE_PRODUCT_SUCCESS";
export const ADMIN_CREATE_PRODUCT_RESET = "ADMIN_CREATE_PRODUCT_RESET";
export const ADMIN_CREATE_PRODUCT_FAIL = "ADMIN_CREATE_PRODUCT_FAIL";

export const ADMIN_EDIT_PRODUCT_REQUEST = "ADMIN_EDIT_PRODUCT_REQUEST";
export const ADMIN_EDIT_PRODUCT_SUCCESS = "ADMIN_EDIT_PRODUCT_SUCCESS";
export const ADMIN_EDIT_PRODUCT_RESET = "ADMIN_EDIT_PRODUCT_RESET";
export const ADMIN_EDIT_PRODUCT_FAIL = "ADMIN_EDIT_PRODUCT_FAIL";

export const ADMIN_UPDATE_PRODUCT_REQUEST = "ADMIN_UPDATE_PRODUCT_REQUEST";
export const ADMIN_UPDATE_PRODUCT_SUCCESS = "ADMIN_UPDATE_PRODUCT_SUCCESS";
export const ADMIN_UPDATE_PRODUCT_RESET = "ADMIN_UPDATE_PRODUCT_RESET";
export const ADMIN_UPDATE_PRODUCT_FAIL = "ADMIN_UPDATE_PRODUCT_FAIL";

export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_RESET = "ADD_REVIEW_RESET";
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
